---
- name: "ensure the ansiblekick user exists"
  user: name="ansiblekick" createhome=yes state=present

- name: "ensure the .ssh directory exists"
  file: path="/home/ansiblekick/.ssh" owner=ansiblekick group=ansiblekick
        mode=0700 state=directory 

- name: "ensure the authorized_keys file is correct"
  copy: src="/etc/ansible/ssh_keys/ansible_kick_authorized_keys"
        dest="/home/ansiblekick/.ssh/authorized_keys"
        owner=ansiblekick group=ansiblekick mode=0644

- name: "ensure the ansible-kick conf dir exists"
  file: path="/etc/ansible-kick" owner=ansiblekick group=ansiblekick
        state=directory

- name: "ensure ansible-kick.conf is correct"
  template: src="ansible-kick.conf.j2" dest="/etc/ansible-kick/ansible-kick.conf"
            owner=root group=root mode=0644

- name: "ensure ansible hosts template is correct"
  copy: src="hosts.tmpl" dest="/etc/ansible-kick/hosts.tmpl"
        owner=root group=root mode=0644
